export const STEPS = {
    WELCOME: 'WELCOME_STEP',
    // NAME: 'NAME_STEP',
    STRUGGLES: 'STRUGGLES_STEP',
    IMPROVEMENTS: 'IMPROVEMENTS_STEP',
    // HABITS: 'HABITS_STEP',
    HABIT_TRACKER: 'HABIT_TRACKER_STEP',
    SAVE_PROGRESS: 'SAVE_PROGRESS_STEP',
   SIGN_UP: 'SIGN_UP_STEP',
   LOG_IN: 'LOG_IN_STEP',
   HOME: 'HOME_STEP',
}